### ISSUE TITLE
open current file by default

### ISSUE THREAD

**Issue by thiagosouza** [mrodalgaard/atom-todo-show#111]
I think is a good idea to open just the current file by default, or having an option for that (this initial config could have current file, project, everything).
Thanks for listening and btw congrats for the great module!

**Comment by mrodalgaard** [comment]
Do you mean a 4th command (currently only 3; `Todo Show: Find In Workspace`, `Todo Show: Find In Project` and `Todo Show: Find In Open Files`) to open the todo list and set the scope to `Active File`? This is the only scope option not directly accessible from the command palette, because I think most cases are covered by `Find in Open Files` - and you can still just click the scope button at the top of the list.

I am not going to change the default from `Find In Workspace`, because it's going to be the command most people are expecting and using.

**Comment by mrodalgaard** [comment]
I have added `find-in-active-file` to the activation commands. So you can now start *todo-show* with the active file setting.

If you want to change the default keybinding of <kbd>CTRL</kbd> + <kbd>SHIFT</kbd> + <kbd>T</kbd> (on Mac) to this setting, add something similar as below to your application `config.cson`:

```
'.platform-darwin atom-workspace':
  'ctrl-shift-t': 'todo-show:find-in-open-files'
```
