### ISSUE TITLE
feature request: show TODO counter in bottom status bar

### ISSUE THREAD

**Issue by cdaringe** [mrodalgaard/atom-todo-show#123]
hello!

thanks for the great lib! i was thinking it would be lovely to have an option to append `TODO: ${count}` the the status bar.  i often am wondering "how many loose ends" did I leave in this project, regardless of whether it's tested or not.  intellij i think has a little TODO pane.  the table interface is GREAT. it would be cool to click the status bar counter and have it open the table as already supported

thanks for your time and consideration

**Comment by mrodalgaard** [comment]
This is a valid feature request. Though it would only work when the todo list is already open, since it can be a pretty expensive operation to search for workspace todos and I do not want to run that as a background task.

I previously had the tab bar show the number of current todos, but it was kind of a hack so I changed it to be shown just below the search field.

**Comment by cdaringe** [comment]
dude... that's awesome!  thanks so much!
