### ISSUE TITLE
CRASH: Todo Show: Find in Project crashes the editor!

### ISSUE THREAD

**Issue by sbrl** [mrodalgaard/atom-todo-show#137]
I've just installed this package, and the "Find in project" function crashes my editor! I can't seem to find any crash reports, but if you can tell me where they are located I'll post them here.

**OS:** Windows 10

**Comment by mrodalgaard** [comment]
Uhh, Windows 10, I don't really have a way of testing that, since all I have is a Windows 7 VM, which does not seem to crash. Does it just instantly crash? Have you tried running `Todo Show: Find In Active File` instead of searching whole workspace? Maybe try running Atom in safe-mode?

It seems from https://discuss.atom.io/t/how-to-debug-crashes-in-windows/28357 Atom crash logs are written to standard OS logging system, and https://www.reddit.com/r/Windows10/comments/3eo2e5/viewing_crash_log/ describes how to read these. I do not have any experience in this area.

**Comment by sbrl** [comment]
Hum. It looks like it fixed itself! I'll reopen this if it comes back 😃
