### ISSUE TITLE
Do not clip the TODO comments in Markdown export; it hides valuable information and breaks Markdown syntax

### ISSUE THREAD

**Issue by sompylasar** [mrodalgaard/atom-todo-show#145]
Example:

```
- __NOTE__ _@sompylasar_ The `display: inline-block;` here to have this element size match its content, i.e. the image itself, so that the `to...
```

Result:
- __NOTE__ _@sompylasar_ The `display: inline-block;` here to have this element size match its content, i.e. the image itself, so that the `to...

**Comment by mrodalgaard** [comment]
Hi @sompylasar. You can use `All` instead of `Text` in `showInTable` config. This should include the whole found line (including the todo text itself, which is not perfect). Try it out.

NB: I think I spotted a bug in the current published version with the `All` setting, which in some situations sat it to the same as `Text`. This will be fixed in the upcoming version.
