### ISSUE TITLE
Add support for LaTeX commands

### ISSUE THREAD

**Issue by colematt** [mrodalgaard/atom-todo-show#159]
In the LaTeX typesetting language, there are several packages that support adding to-do annotations to the document. See [here](http://ctan.mackichan.com/macros/latex/contrib/todonotes/todonotes.pdf) for one such example.

The problem is that the format of the todo markup (`\todo{Your to-do message here}`) isn't captured by the `atom-todo-show` package in its current state. I tried everything I could think of in the **Find Todos** option text including, but not limited to:
- `todo`
- `\todo`
- `\\todo`
- `\\todo{\\d*}`

Can this markup be supported by the current Atom package?

**Comment by mrodalgaard** [comment]
If `\todo {Your to-do message here}` (with a space after todo) is an accepted format in LaTeX, then you can solve it by simply adding `'todo'` to the `findTheseTodos` config.

Otherwise you have to edit the `findUsingRegex` config to accept todos not followed by a space. Something like `"/\\b(${TODOS})[:;.,]?\\d*($|\\s.*$|\\(.*$|[\\{\\[].+$)/g"` would work. I might change this is the future to accept todos followed by brackets, but I will never add lowercase `todo` to the default todos to find.

**Comment by colematt** [comment]
Thanks, that should do the trick!
