### ISSUE TITLE
Only rescan saved files

### ISSUE THREAD

**Issue by steronydh** [mrodalgaard/atom-todo-show#164]
Similar to #156, on save could todo-show just re-scan the saved files instead of scanning everything on every save?

**Comment by mrodalgaard** [comment]
I have added a config option for auto refreshing on save. I have previously toyed around with a solution for only rescanning the changed files, because it made a lot of sense. Though without luck - it kept coming in situations where the todo list was out of sync with the files. I will take this up again when I get the time. Thank you for the feedback.
