### ISSUE TITLE
Weird pane/empty space display bug

### ISSUE THREAD

**Issue by ffxsam** [mrodalgaard/atom-todo-show#169]
Tough to describe, so here's a screencap:

![screenflow](https://user-images.githubusercontent.com/12532733/28044433-f94a4ed2-659c-11e7-9631-e64565d2ec1c.gif)

**Comment by voxpelli** [comment]
I had the same issue and after some debugging I discovered that it was due to a value stored by this plugin in its local storage to restore some view size and that the value resulted in that very bug that you are seeing there when it was being set.

I didn't debug it further when I realized that disabling the `Remember View Size` option in the settings of this plugin was enough to get rid of the bug.

**Comment by mrodalgaard** [comment]
Hi @ffxsam, disabling RememberViewSize should fix the problem. But the next version of todo-show has a major improvement to the todo-show view. It uses the new Atom Dock to show the pane, which should streamline and solve all these view issues.
