### ISSUE TITLE
Please support markdown

### ISSUE THREAD

**Issue by youngjuning** [mrodalgaard/atom-todo-show#182]

**Comment by mrodalgaard** [comment]
@youngjuning where should we support markdown? In the todos? How would that work?

**Comment by sati-bodhi** [comment]
One caveat - perhaps specific to markdown - is this: 
While I can do one comment per line, multiple comments in a line fail to work. 

```
<!-- NOTE: This works. -->

But multiple comments in a line<!-- NOTE: Like this --> doesn't. <!-- QUESTION: Why？ -->
```

![default](https://user-images.githubusercontent.com/7592695/39337919-4de580bc-49f2-11e8-878c-8590201d3317.png)

Tried tweaking the default regex to make this work, but no success yet.

**Comment by drnikki** [comment]
Confirmed ^ a todo statement inline isn't picked up by the plugin.   I'm dropping a [TODO: lorem ipsum] into paragraphs of text, and would love to have some way to pick up just the text between the : and the ] (in my case) or the : and the --> in @sati-bodhi 's case

**Comment by mrodalgaard** [comment]
`[TODO: lorem ipsum] ` inside markdown text is picked up just fine (but with the last `]` is included as you mention). The package does some magic stripping of ending characters (regex `/(\*\/}?|\?>|-->|#>|-}|\]\])\s*$/`). It takes the rest of the line as a comment to the todo, because that is the normal behaviour for code. I think putting todos inside text / code is an anti-pattern in general.

I might look into making the stripping and end characters configurable, but that has to be another issue opened.
