### ISSUE TITLE
Add 'Right-click' > Mark as Done Option to 'TODO Show' Pane

### ISSUE THREAD

**Issue by drew0530** [mrodalgaard/atom-todo-show#190]
It would be nice, (just as an aesthetic), to be able to right click a TODO in the "Show" Pane were all the TODOs are listed, and the drop-down to include a "Mark as Complete" option, that would remove the TODO tag and possibly even the comment. 

I could see how the removal of the comment could be problematic to some users that may only want the tag to be removed, so maybe add a check-able option in the settings to either just remove the TODO tag, or the whole comment associated with it as well. The default for that should probably just be to remove the tag, so no-one who isn't expecting it to fully remove their comment isn't negatively affected by this. :)

I played around lightly to do this, just so if what I am saying 
![image](https://user-images.githubusercontent.com/25624473/36809683-9c8d6fce-1c96-11e8-955b-49cd187e2e8d.png)

**Comment by mrodalgaard** [comment]
I do not think this is helpful enough. Fully removing the todo is too aggressive as you also mention, and removing the todo tag does not make sense, because then the comment from the todo is left behind which is never what you wish.

The job can be done by clicking the todo (which jumps to the line) and then the user can do whatever he wish.

To complete a todo you almost always need to change the code adjacent to it or add a new comment.
