### ISSUE TITLE
Ignore These Paths, removes defaults with new definition

### ISSUE THREAD

**Issue by TrevorJTClarke** [mrodalgaard/atom-todo-show#65]
I defined paths in the settings field, and everything works fine.
I noticed the default paths inside the input, and expected them to be in addition to the ones I specify. 

Is there a way to make it so the defaults dont have to be set in addition to my settings?
thanks!!

**Comment by mrodalgaard** [comment]
I have looked at this, but the problem is that then you won't be able to remove the defaults if you do not like them.

As I see it the only real solution is writing the defaults to config.cson at first start, but that might also irritate some users.

I have not found other packages solving this in a reasonable way.

**Comment by TrevorJTClarke** [comment]
I see. I like the option for config.cson, would there be a way to setup the default cson file, and then link it in the settings? Then users could modify to meet their needs. 
So far loving the plugin!

**Comment by mrodalgaard** [comment]
Look at https://discuss.atom.io/t/extend-config/19448

I still believe the current solution is the best for now. But lets see where the discussion goes.

**Comment by TrevorJTClarke** [comment]
Got it, hopefully this becomes part of a future release once the atom team finishes their stability phase.
thanks!!

**Comment by mrodalgaard** [comment]
This is default behaviour in Atom config now 🎉
