### ISSUE TITLE
Optional white-space after the colon

### ISSUE THREAD

**Issue by syerad** [mrodalgaard/atom-todo-show#96]
Is there a reason why the white-space after the colon is non-optional.
I think it would be nice to modify the regex to match also the TODOS without a white-space after the colon.

**Comment by mrodalgaard** [comment]
It was originally removed because it resulted in some false positives (very rare occasion, I agree) and it was grammatically incorrect. I do not think I will change this in the default regex expression, but it is customisable for each user, so you are welcome to change each expression to something like `/\\b@?TODO:?\\d?($|\\s.*$)/g` instead.
