### ISSUE TITLE
Crash on workspace selection

### ISSUE THREAD

**Issue by StefanoWoerner** [mrodalgaard/atom-todo-show#98]
First of all: very useful package, thanks!

But there seems to be a slight problem (at least on my system):
When I open up the TODO pane with the default scope "workspace", Atom first uses up all of my RAM and then crashes. Searching for TODOs in open files or in the current file works well, it is just the search in the whole workspace that causes problems. When I select one of the working options, the RAM goes back to normal and all works well. When I then select workspace again, the problem shows again.
Out of curiosity: What exactly do you define as "workspace"? I don't really get it, is workspace the same as the current project? And that again would be the current folder I am working in, right?

I have no clue on what is causing the Issue, but I would really appreciate a fix.

**Comment by mrodalgaard** [comment]
Thank you.

By workspace we mean the currently opened project(s) root and up. If you have a veery huge codebase, opened a large number of projects or have some binary files that does not get marked as binary in your opened project we have seen that the search can take a long time and even make Atom non-responsive.

Inside todo-show we use the same mechanism as used by [find-and-replace](https://github.com/atom/find-and-replace) to search for tags like TODO and FIXME. If you open the project you are having problems with and use `Project Find: Show` you are probably seeing somewhat the same behaviour (although less severe, because you only search for one keyword).

We are working on a way to search for all tags with a single roundtrip / regex query (and still have the regex customisable), which would majorly improve this issue for very large projects.

**Comment by mrodalgaard** [comment]
Next release has a major performance improvement, which should help on what you are observing. I will close this issue and reopen if requested again.
